name: Release

on:
  push:
    branches:
      - main
      - prerelease

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TRANSCODES_CDN_BASE: ${{ secrets.TRANSCODES_CDN_BASE }}

    steps:
      - name: checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_CHANGESET_TOKEN }}
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: npm ci
      - name: Create release pull request
        id: changeset_action
        uses: changesets/action@v1
        with:
          publish: npm run release-package
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CHANGESET_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_CHANGESET_TOKEN }}
